#!/usr/bin/env bash
# Data Download Guide for WCP-L2D
# Both datasets require registration before downloading.
set -euo pipefail

DATA_DIR="$(cd "$(dirname "$0")/.." && pwd)/data"

echo "============================================"
echo "  WCP-L2D Data Download Guide"
echo "============================================"
echo ""
echo "Target directory: ${DATA_DIR}"
echo ""

echo "=== 1. CheXpert Dataset (Source Domain) ==="
echo ""
echo "Download from Kaggle:"
echo "  https://www.kaggle.com/datasets/ashery/chexpert"
echo ""
echo "Download: CheXpert-v1.0-small.zip (~11GB)"
echo "Extract to: ${DATA_DIR}/CheXpert-v1.0-small/"
echo ""
echo "Expected structure:"
echo "  ${DATA_DIR}/CheXpert-v1.0-small/"
echo "    train/"
echo "      patient00001/"
echo "        study1/"
echo "          view1_frontal.jpg"
echo ""

echo "=== 2. NIH ChestX-ray14 Dataset (Target Domain) ==="
echo ""
echo "Option A - Full resolution from Academic Torrents:"
echo "  https://academictorrents.com/details/557481faacd824c83fbf57dcf7b6da9383b3235a"
echo ""
echo "Option B - Pre-resized 224x224 (smaller, recommended) via Academic Torrents:"
echo "  https://academictorrents.com/details/e615d3aebce373f1dc8bd9d11064da55bdadede0"
echo ""
echo "Option C - Pre-resized 224x224 from Kaggle:"
echo "  https://www.kaggle.com/datasets/khanfashee/nih-chest-x-ray-14-224x224-resized"
echo ""
echo "If you have the kaggle CLI installed and configured (place ~/.kaggle/kaggle.json or set KAGGLE_USERNAME/KAGGLE_KEY), you can download and unzip directly:"
echo "  mkdir -p ${DATA_DIR}/NIH"
echo "  kaggle datasets download -d khanfashee/nih-chest-x-ray-14-224x224-resized -p ${DATA_DIR}/NIH --unzip"
echo ""
echo "Extract images to: ${DATA_DIR}/NIH/images/  (the kaggle dataset above should create the images/ folder when unzipped)"
echo ""
echo "Expected structure:"
echo "  ${DATA_DIR}/NIH/images/"
echo "    00000001_000.png"
echo "    00000001_001.png"
echo "    ..."
echo ""

echo "=== 3. After downloading, run feature extraction ==="
echo ""
echo "  uv run python scripts/extract_features.py --dataset chexpert --imgpath ${DATA_DIR}/CheXpert-v1.0-small"
echo "  uv run python scripts/extract_features.py --dataset nih --imgpath ${DATA_DIR}/NIH/images"
echo ""
echo "Features will be saved to: ${DATA_DIR}/features/"
